### ISSUE TITLE
Script compilation fails with Scala 2.11

### ISSUE THREAD

**Issue by galderz** [vert-x/mod-lang-scala#171]
Script compilation fails with Scala 2.11:

```
/Users/g/Go/demos/vertx-examples.git/src/raw/scala/echo/EchoClient.scala:17: error: expected class or object definition
vertx.createNetClient.connect(8080, "localhost", { asyncResult: AsyncResult[NetSocket] =>
^
```

The issue is related to how the variables are bound in the Scala interpreter when running as quiet. Instead of `NamedParamClass`, `NamedParam` was being used which works fine with Scala 2.10.

A workaround is to enable verbose compilation via -Dvertx.scala.interpreter.verbose=true
